spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/batch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  application:
    name: pooney
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh


