spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy
